package Vistas;

import Controlladores.Tiene_Capacidad;
import Modelos.Frutas_Verduras;
import Modelos.Tamano_Contenedor;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author crist
 */
public class Llenando_Jugo extends javax.swing.JFrame {
    
    private int sabor;
    private int tamano;
    private int tipo;
    
    public Llenando_Jugo(int sabor, int tamano, int tipo){
        this.sabor = sabor;
        this.tamano = tamano;
        this.tipo = tipo;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private Llenando_Jugo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Extrayendo jugo");
        setLocation(new java.awt.Point(200, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Llenando contenedor");

        progreso_llenado.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progreso_llenado, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(progreso_llenado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Thread runner = new Thread() {
            public void run() {
                int counter = 0, progreso = 0; boolean esta_lleno = false;
                Tiene_Capacidad checar = new Tiene_Capacidad();
                Tamano_Contenedor resivir = new Tamano_Contenedor();
                int ml = resivir.getTamano_Actual(tamano);
                while (counter < ml) {
                    progreso_llenado.setValue(progreso);
                    counter = checar.Llenar(sabor, tamano, counter);
                    double ps = (Double.parseDouble( String.valueOf(counter)) / Double.parseDouble(String.valueOf(ml)))*100;
                    progreso = (int) ps;
                    try {
                        Thread.sleep(100);
                    } catch (Exception ex) {}
                }
                if(counter > ml){
                    administrar_vistas("Se derramo el jugo ¿Deseeas otro jugo?");
                }else{
                    administrar_vistas("¿Deseeas otro jugo?");
                }
                Frutas_Verduras reducir = new Frutas_Verduras();
                reducir.setCantidad_Restante(sabor, counter);
            }
        };
        runner.start();
    }//GEN-LAST:event_formWindowOpened
    
    private void administrar_vistas(String pregunta){
        int respuesta = (int) JOptionPane.showConfirmDialog(null, pregunta, "opcion", ConfirmationCallback.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        this.setVisible(false);
        if(respuesta == 0){
            Menu llamar_vista = new Menu();
            llamar_vista.setVisible(true);
        }else{
            Bienvenido llamar_vista = new Bienvenido();
            llamar_vista.setVisible(true);    
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Llenando_Jugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Llenando_Jugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Llenando_Jugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Llenando_Jugo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Llenando_Jugo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private final javax.swing.JProgressBar progreso_llenado = new javax.swing.JProgressBar();
    // End of variables declaration//GEN-END:variables
}
