/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controlladores.Tiene_Jugo;
import Modelos.Frutas_Verduras;
import Modelos.Tamano_Contenedor;
import Modelos.Tipo_Contenedor;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private String sabores [] = new Frutas_Verduras().getArreglo_Sabores();
    private String tamano [] = new Tamano_Contenedor().getArray_Tamano();
    private String contenedores [] = new Tipo_Contenedor().getArray_Tipos();
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opciones_sabor = new javax.swing.JComboBox<>();
        Titulo = new javax.swing.JLabel();
        texto_tipo_contendor = new javax.swing.JLabel();
        texto_tamaño = new javax.swing.JLabel();
        opciones_tamano = new javax.swing.JComboBox<>();
        text_Sabor = new javax.swing.JLabel();
        opciones_contendores = new javax.swing.JComboBox<>();
        Pagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));

        opciones_sabor.setModel(new javax.swing.DefaultComboBoxModel<>(sabores));

        Titulo.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Configurar jugo");

        texto_tipo_contendor.setText("Tipo de contenedor");

        texto_tamaño.setText("Tamaño del contenedor");

        opciones_tamano.setModel(new javax.swing.DefaultComboBoxModel<>(tamano));

        text_Sabor.setText("Sabor del jugo");

        opciones_contendores.setModel(new javax.swing.DefaultComboBoxModel<>(contenedores));

        Pagar.setText("Pagar");
        Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto_tamaño)
                            .addComponent(opciones_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opciones_contendores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(texto_tipo_contendor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(opciones_sabor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(text_Sabor))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_Sabor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opciones_sabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(texto_tamaño)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opciones_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(texto_tipo_contendor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opciones_contendores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarActionPerformed
        Tiene_Jugo llamar = new Tiene_Jugo();
        if( llamar.Checar_Stock_General(opciones_sabor.getSelectedIndex()) )
           JOptionPane.showMessageDialog(null, "El sabor que eligio ya no tiene jugo", "Sin jugo", JOptionPane.INFORMATION_MESSAGE);
        else if( llamar.Checar_Stock_Tamano(opciones_sabor.getSelectedIndex(), opciones_tamano.getSelectedIndex()) )
            JOptionPane.showMessageDialog(null, "Ya no hay jugo para ese tamaño", "Sin capacidad", JOptionPane.INFORMATION_MESSAGE);
        else{
            this.setVisible(false);
            new Llenando_Jugo(opciones_sabor.getSelectedIndex(), opciones_tamano.getSelectedIndex(), opciones_contendores.getSelectedIndex() ).setVisible(true);
        }
    }//GEN-LAST:event_PagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pagar;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> opciones_contendores;
    private javax.swing.JComboBox<String> opciones_sabor;
    private javax.swing.JComboBox<String> opciones_tamano;
    private javax.swing.JLabel text_Sabor;
    private javax.swing.JLabel texto_tamaño;
    private javax.swing.JLabel texto_tipo_contendor;
    // End of variables declaration//GEN-END:variables
}
